/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SleeknoteUI;



/**
 *
 * @author vinic
 */
public class TelaInicial extends javax.swing.JPanel {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BntAbrirCaixa = new javax.swing.JButton();
        BntProdutos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        BntAbrirCaixa.setBackground(new java.awt.Color(255, 153, 51));
        BntAbrirCaixa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BntAbrirCaixa.setForeground(new java.awt.Color(255, 255, 255));
        BntAbrirCaixa.setText("Abrir Caixa");
        BntAbrirCaixa.addActionListener(this::BntAbrirCaixaActionPerformed);

        BntProdutos.setBackground(new java.awt.Color(255, 153, 51));
        BntProdutos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BntProdutos.setForeground(new java.awt.Color(255, 255, 255));
        BntProdutos.setText("Produtos");
        BntProdutos.addActionListener(this::BntProdutosActionPerformed);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_256x256.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(BntAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(BntProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(554, 554, 554)
                        .addComponent(jLabel2)))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntAbrirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BntProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(242, 242, 242))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BntAbrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAbrirCaixaActionPerformed
        // TODO add your handling code here:
        TelaVendas tela = new TelaVendas();

    tela.setSize(this.getSize());

    this.removeAll();

    this.setLayout(new java.awt.BorderLayout());

    this.add(tela, java.awt.BorderLayout.CENTER);

    this.revalidate();

    this.repaint();
    }//GEN-LAST:event_BntAbrirCaixaActionPerformed

    private void BntProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntProdutosActionPerformed
        // TODO add your handling code here:
        TelaProduto tela = new TelaProduto();
    tela.setSize(this.getSize());
    
    this.removeAll();
    
    this.setLayout(new java.awt.BorderLayout());
    
    this.add(tela, java.awt.BorderLayout.CENTER);
    
    this.revalidate();
    
    this.repaint();
        
    }//GEN-LAST:event_BntProdutosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntAbrirCaixa;
    private javax.swing.JButton BntProdutos;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
